# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name:                waspc
version:             0.2.2.2 # %WASP_VERSION% - annotation for new-release script.
github:              "Martinsos/waspc"
license:             MIT
author:              "wasp-lang"
maintainer:          "sosic.martin@gmail.com, matija.sosic@gmail.com"
copyright:           "2020 wasp-lang"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Martinsos/waspc#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -optP-Wno-nonportable-include-path # To avoid warning caused by .../autogen/cabal_macros.h. on OSX.

library:
  source-dirs: src
  dependencies:
    - filepath

executables:
  wasp:
    main:                Main.hs
    source-dirs:         cli 
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - waspc
